### ISSUE TITLE
Big repository / tree

### ISSUE THREAD

**Issue by DanielRuf** [ghuser-io/ghuser.io#146]
Currently this project is around 34MB big.

**Comment by AurelienLourot** [comment]
Indeed it's becoming urgent that I do something about it :)

**Comment by DanielRuf** [comment]
I'll do a short analysis. In general we can not rewrite the history (just on / with a new clean branch).

**Comment by DanielRuf** [comment]
Hm, not sure if this can be also done with Enhanced GitHub and Refined GitHub.
It seems we are cloning GitHub here.

**Comment by AurelienLourot** [comment]
It's because the DB is a set of json files in `db/`, which was OK as long as we had only a few users. We need to move that to a real DB or at least to a separate repo

**Comment by AurelienLourot** [comment]
50M -> 16M

DB is now [here](https://github.com/ghuser-io/db). Still json files but that will also be improved eventually. Thanks for this issue!
