### ISSUE TITLE
Profile for vividvilla

### ISSUE THREAD

**Issue by vividvilla** [ghuser-io/ghuser.io#154]
I'd like to have my profile on ghuser.io, thanks!

**Comment by wopian** [comment]
Me too, if its not too soon yet 👍

**Comment by mkg20001** [comment]
Same :+1:

**Comment by AurelienLourot** [comment]
here you go :)

* https://ghuser.io/vividvilla
* https://ghuser.io/wopian
* https://ghuser.io/mkg20001

**Comment by neo** [comment]
😳

**Comment by maple3142** [comment]
Same :+1:

**Comment by AurelienLourot** [comment]
@maple3142 https://ghuser.io/maple3142 :)
