### ISSUE TITLE
Slow on firefox

### ISSUE THREAD

**Issue by AurelienLourot** [ghuser-io/ghuser.io#161]
Especially the new collapsible that came in with #158. Noticed both on Ubuntu and on macOS.

**Comment by brillout** [comment]
Was it faster before? Like the old one, the new frontend uses semantic UI's collapsible

**Comment by AurelienLourot** [comment]
Just checked by running locally the version just before (94048f4). It was a bit better before indeed, not perfect, but noticeably less sluggish.

**Comment by brillout** [comment]
I notice
 - The collapsible is indeed sluggish
 - When the cache is empty the initial page load is very slow. (When the cache is filled the page load time is okay-ish.) Notably the `orgs.json` seems to take a longer time to download on firefox.
 - The rendering of the page takes more time on firefox but is okay-ish

So basically the two slow things are the collapsible and the empty-cache initial-load. Or did you notice other slowness?

**Comment by AurelienLourot** [comment]
:+1: I'm picking up the `orgs.json` issue https://github.com/ghuser-io/db/issues/15
