### ISSUE TITLE
github-contribs is broken

### ISSUE THREAD

**Issue by AurelienLourot** [ghuser-io/ghuser.io#172]
[github-contribs](https://github.com/ghuser-io/github-contribs)'s tests turned red yesterday, because the unofficial interface to discover pull-requests seems to have changed.

So the last time we know for sure that the interface hadn't changed yet is October 10th 9:38AM UTC.

We need to:
* fix `github-contribs` and pin the latest version here in ghuser,
* re-crawl the recent days of all users,
* re-crawl completely all users created since October 10th 9:38AM UTC.

**Comment by brillout** [comment]
We don't know how to properly set the header to be able to get these bigger HTML parts. Plus the structure of these bigger HTML parts are very likely to change.

So we will use the graphql api to get the list of all pull requests.

**Comment by AurelienLourot** [comment]
I got the big HTML parsing working. Not the best solution but this unblocks us for the short-term. Updated todo-list:

* [x] fix `github-contribs`,
* [ ] pin the latest version here in ghuser,
* [ ] re-crawl the recent days of all users,
* [ ] re-crawl completely all users created since October 10th 9:38AM UTC.
