### ISSUE TITLE
username update issue

### ISSUE THREAD

**Issue by Ishaan28malik** [ghuser-io/ghuser.io#184]
I recently updated my GIthub username but it was not updated by the ghuser server please check and fix this issue. @styfle @trel @jamesgeorge007 .

**Comment by AurelienLourot** [comment]
Hi @Ishaan28malik, your username is `Ishaan28malik` and https://ghuser.io/Ishaan28malik looks good. Am I missing something?

**Comment by Ishaan28malik** [comment]
@AurelienLourot It got update and sorry I was refering to my display name and I just observed that it just took a day to get updated .
