### ISSUE TITLE
Allow links to keybase profiles from ghuser profiles

### ISSUE THREAD

**Issue by nealmcb** [ghuser-io/ghuser.io#191]
Keybase is a compelling secure user-centric identity / collaboration / chat / encrypted git / ... hub with an open source client.

Allow users to point to their keybase profiles (e.g. https://keybase.io/nealmcb) from their ghuser profiles (e.g. https://ghuser.io/nealmcb) in their ghuser.io.settings repo fork.

https://github.com/ghuser-io/ghuser.io/blob/master/docs/user-settings.md

**Comment by sharontlin** [comment]
I'd be happy to take this on! I can issue a pull request with the change.

**Comment by lourot** [comment]
Thank you @sharontlin !
