### ISSUE TITLE
Contribution percentage is too hidden

### ISSUE THREAD

**Issue by AurelienLourot** [ghuser-io/ghuser.io#36]
Follow-up on #20. For now there are several ways of seeing the contribution percentage:
* at the first glance the [owner] badge tells you the dev made more than 85% of the commits, the [maintainer] badge tells you they made more than 15%, and no badge tells you they made less.
* if you hover the badge you see the percentage
* if you open the details of a contribution you see the percentage.

@brillout thinks the number should already be visible at the first glance.

**Comment by brillout** [comment]
Yea I'd be obsessive about the first glance experience. What infos exactly do we want the user to get at first glance? To me it's the whole programming resume thingy. I could see to love it so much when/if this becomes the case. That's only me though

**Comment by AurelienLourot** [comment]
@brillout still valid now after https://github.com/ghuser-io/ghuser.io/pull/158 ?

**Comment by brillout** [comment]
I'd say that the crown and medals are a good enough first impression of how much a user contributed to a repo. And the exact percentage is shown when expending a contrib.
